[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "multiaddr",
    "appdirs",
    "idna"  ,
    "httpcore==0.14.7",
    "httpx==0.22.0",
    "requests"
]
build-backend = "setuptools.build_meta"
